### ISSUE TITLE
where is glove_embeds.py & bug report

### ISSUE THREAD

**Issue by Tengyang-Chen** [ajamjoom/Image-Captions#1]
Thanks for sharing your project.
Would you tell me where can I find glove_embeds.py.
and bug report
main.py Line 316
- decoder = Decoder(vocab_size=len(vocab),use_glove=use_glove, use_bert=use_bert).to(device)
+ decoder = Decoder(vocab_size=len(vocab),use_glove=glove_model, use_bert=bert_model).to(device)

when from_checkpoint set to False, [use_glove=use_glove, use_bert=use_bert] will raises error.

**Comment by ajamjoom** [comment]
Apologies for the late reply, I've just pushed the glove_embeds.py file. I somehow forgot to push it. I've also pushed a bug fix, thank's for raising the issue!
